### ISSUE TITLE
Move location of output packages (Install/Source) from \bin to \install

### ISSUE THREAD

**Issue by nvisionative** [dazinator/DnnPackager#52]
This will be a more intuitive location for output packages.  The \bin directory is a special one and should be reserved for typical files (*.dll, *.pdb, etc.).

**Comment by dazinator** [comment]
Interesting - thanks for the suggestion. I do have some reservations about this one though :-)

My concern would be that creating an additional install folder and outputting to that would cause the zip file to show up on source control check-ins which is not really what you want, where as the bin folder is a well known directory that is usually ignored. So this would mean source control users will have to add rules to exclude this additional folder where as currently they shouldn't have to worry. Due to this there should be a really compelling reason for this change.

Personally i'm used to checking the bin folder for build output, and to me, a seperate folder for the zip file output is less intuitive :-) - perhaps im an oddball, but the bin folder would be the first place i'd check if I was a brand new dnn module developer and had to guess at where the zip was output.

As for the bin folder containing just dll, pdb etc, xamarin projects also spit out install packages (apk files for example) to the bin directory so it's not unheard of.

Also what if the project has a folder called "install"   already, with install scripts and such in. Perhaps that won't be common, but right now by using the bin folder i don't have to worry about anything like that..
Happy to be convinced if some of these concerns can be addressed!

**Comment by nvisionative** [comment]
I hear and respect your thoughts on the matter.  I just know many of your "audience" will be familiar with the way it has always been done with the most popular DNN module template, and will just expect the install/source packages to be in the \install directory.  That directory is not usually included in the project though, so I'm not sure if that helps your concern about source control or not.

**Comment by dazinator** [comment]
Yeah you are right about this being a "dnn'ism" that pople may have grown used too. But I'm happy with the decision for using the bin folder, for the reasons i mentioned. I'm closing this one for now.
