### ISSUE TITLE
Auto-build manifest file

### ISSUE THREAD

**Issue by david-poindexter** [dazinator/DnnPackager#58]
@dazinator not sure if you have looked into this possibility or not, but thought I would at least log it for consideration.  I ran across some work being done by XCESS [here](https://github.com/XCESS-NL/MSBuild-for-DNN) and thought it was a great idea.  It would be nice to not have to manually maintain the manifest file.  Your thoughts?

**Comment by dazinator** [comment]
Yep this makes sense to me. I have considered auto building the manifest using attributes, and I have [created a library here](https://github.com/dazinator/Dazinate.Dnn) that can be used to programatically build a manifest and then save it to xml.  

So for me this definately makes sense as a feature for DnnPackager, i.e during the current packaging task it can:
1. Inspect the primary output assembly for known attibutes (Like a `Module` attribute, or a `Library` attribute etc)
2. Auto build the manifest based on the information provided by those attributes.

One concern with this approach is that I don't like the idea that you would have to reference the assembly containing these attributes in your module / project, because that means you also have to deploy this additional assembly with your module - when it really is only needed at build time - it's now become a runtime dependency.

As you can imagine, if you have one module installed using 1 version of this attributes assembly, and then you install another module using a slightly later version of that attributes assembly - there can only be one version of it in the bin folder, so something will break in that scenario.

I think there are a couple of solutions to eliminate the runtime dependency on the attributes assembly:
1. Make the NuGet package add the actual source code files for the attributes to your project - this way they get compiled with your own component and it eliminates the assembly dependency. 
2. Use something like Fody.Weaver to run during build, and clean the attributes from the output assembly. (MSIL manipulation at build time)

Also the amount of attributes that you would need to represent the manifest could be quite a lot.. Would have to think very carefully about the attributes themselves and how to make them simple but effective!

**Comment by dazinator** [comment]
This is also very similar to how Xamarin projects work for Android applications so it should be kind of familiar for those developers.. You can manually edit the android application manifest, but you can also use attributes to suppliment the manifest data.

**Comment by dazinator** [comment]
Will close this as decided will want to go ahead with this. Read #60 for further info about how I see this working.

**Comment by david-poindexter** [comment]
Thanks @dazinator!
